[tool.black]
line-length = 100
exclude = '''
/(
   \.git
 | \.github
 | .*\.egg-info
 | dist
 | venv
 )/
'''

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
