name: CI

on:
  push:  # only run on push to main
    branches: [main]
  pull_request:  # open between any two branches

jobs:
  test:
    name: "Test: Python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r tests/requirements_test.txt
      - name: Install Cleanlab Studio client
        run: pip install -e .
      - name: Set env variables (Linux/macOS/Windows)
        run: |
          echo "CLEANLAB_API_BASE_URL=${{ secrets.CLEANLAB_API_BASE_URL }}" >> $GITHUB_ENV
        shell: bash
      - name: Cleanlab login
        run:  cleanlab login --key "${{ secrets.CLEANLAB_STUDIO_CI_API_KEY }}"
      - name: Run tests
        run: |
          pytest --verbose
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install . # install deps
          pip install mypy
          mypy --install-types --non-interactive cleanlab_studio
      - run: mypy --strict cleanlab_studio
  launch-tlm-test-notif:
    name: Comment TLM test start on PR
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        id: fc
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-regex: '^/test-tlm$'
          direction: last
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        if: steps.fc.outputs.comment-id == ''
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :sparkles: **Starting TLM tests...** :sparkles:
            If you want to run the TLM tests again (in case they failed or you have further updates to the TLM code), comment '/test-tlm' on this PR.
            [View full GitHub Actions run log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: rocket
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v4
        if: steps.fc.outputs.comment-id != ''
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            :sparkles: **Starting TLM tests...** :sparkles:
            If you want to run the TLM tests again (in case they failed or you have further updates to the TLM code), comment '/test-tlm' on this PR.
            [View full GitHub Actions run log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: rocket
  finish-tlm-test-notif:
    name: Comment TLM test completion on PR
    runs-on: ubuntu-latest
    needs:
      - launch-tlm-test-notif
      - test
      - typecheck
    steps:
      - name: Find Comment
        id: fc
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Starting TLM tests
          direction: last
      - name: Build Comment Body
        run: |
          # Set up emojis based on test results
          if [[ "${{ needs.test.result }}" == "success" ]]; then
            TLM_TEST_RESULT="✅"
          else
            TLM_TEST_RESULT="❌"
          fi

          if [[ "${{ needs.typecheck.result }}" == "success" ]]; then
            PROPERTY_TEST_RESULT="✅"
          else
            PROPERTY_TEST_RESULT="❌"
          fi

          echo "PROPERTY_TEST_RESULT=$PROPERTY_TEST_RESULT" >> $GITHUB_ENV
          echo "TLM_TEST_RESULT=$TLM_TEST_RESULT" >> $GITHUB_ENV
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            :sparkles: **Tests completed!** :sparkles:
            TLM Tests Results: ${{ env.TLM_TEST_RESULT }}${{ env.TLM_TEST_RESULT }} ${{ env.TLM_TEST_RESULT }}${{ env.TLM_TEST_RESULT }}${{ env.TLM_TEST_RESULT }}
            TLM Property Tests Results: ${{ env.PROPERTY_TEST_RESULT }}${{ env.PROPERTY_TEST_RESULT }}${{ env.PROPERTY_TEST_RESULT }}${{ env.PROPERTY_TEST_RESULT }}${{ env.PROPERTY_TEST_RESULT }}
            Click the Github Actions run log for more information.
