name: CI

on:
  push:  # only run on push to main
    branches: [main]
  pull_request:  # open between any two branches

jobs:
  check-comment:
    name: Fetch Latest Comment
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check latest comment
        run: |
          COMMENT_BODY=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments --jq '.[-1].body')
          echo "Latest comment is: $COMMENT_BODY"
          if [[ "$COMMENT_BODY" == "/test-tlm" ]]; then
            echo "IS_TEST_TLM_COMMENT=true" >> $GITHUB_ENV
          else
            echo "IS_TEST_TLM_COMMENT=false" >> $GITHUB_ENV
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install . # install deps
          pip install mypy
          mypy --install-types --non-interactive cleanlab_studio
      - run: mypy --strict cleanlab_studio
