name: CI

on: [ push, pull_request ]

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install . # install deps
          pip install mypy
          mypy --install-types --non-interactive cleanlab_studio
      - run: mypy --strict cleanlab_studio
