name: CI

on:
  push:  # only run on push to main
    branches: [main]
  pull_request:  # open between any two branches

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install . # install deps
          pip install mypy
          mypy --install-types --non-interactive cleanlab_studio
      - run: mypy --strict cleanlab_studio
  propertytest:
    name: "TLM Property Test TLM: Python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
        python:
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install -r tests/requirements_test.txt
      - name: Install Cleanlab Studio client
        run: pip install -e .
      - name: Set env variables (Linux/macOS/Windows)
        run: |
          echo "CLEANLAB_API_BASE_URL=${{ secrets.CLEANLAB_API_BASE_URL }}" >> $GITHUB_ENV
        shell: bash
      - name: Cleanlab login
        run:  cleanlab login --key "${{ secrets.CLEANLAB_STUDIO_CI_API_KEY }}"
      - name: Run tests
        run: |
          pytest tests/tlm/test_properties.py --verbose
