name: CI

on:
  push:  # only run on push to main
    branches: [main]
  pull_request:  # open between any two branches

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install . # install deps
          pip install mypy
          mypy --install-types --non-interactive cleanlab_studio
      - run: mypy --strict cleanlab_studio
  launch-tlm-test-notif:
    name: Comment TLM test start on PR
    runs-on: ubuntu-latest
    steps:
      - name: Log PR Number
        run: echo "PR Number is ${{ github.event.pull_request.number }}"
      - name: Find Comment
        id: fc
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-regex: '^/test-tlm$'
          direction: last
