name: Tests to run on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  comment-on-pr:
    name: Launch TLM tests on PR
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const commentBody = "/test-tlm";  // The comment you want to post
            const issueNumber = context.issue.number;  // Get the PR number

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody
            });
