name: Tag and release new PyPi package

on:
  push:
    tags:
      - v*

jobs:
  build-and-release-pypi-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install --upgrade build
          pip install --upgrade twine
      - name: Build package
        run: python3 -m build
      - name: Release package
        run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }} --verbose

  update-docs:
    needs: build-and-release-pypi-package
    uses: cleanlab/cleanlab-studio-docs/.github/workflows/build_and_deploy.yml@main
    secrets: inherit
