name: Tag and release new PyPi package

on:
  push:
    branches:
      - main
    tags:
      - v0.*

jobs:
  build-and-releasepypi-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install --upgrade build
          pip install --upgrade twine
      - name: Build package
        run: python3 -m build
      - name: Release package
        run: twine upload dist/* -u TOKEN -p ${{ secrets.PYPI_TOKEN }}
